diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
gui.recentrepo=D:/wamp64/www/dolibarr
gui.recentrepo=D:/wamp64/www/dolibar
user.email=developerjoswin@gmail.com
user.name=matrixbreaker1
safe.directory=C:/Users/joswi
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/gluewell/test_1
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
remote.upstream.url=https://github.com/gluewell/test1.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
